### PR TITLE
add tests to validate working state

### PR DESCRIPTION
**Pull request by paulortman**
I wrote some tests as I familiarized myself with the code.  I figured they might be seen as helpful.

### CODE REVIEW

**Comment by davegaeddert** [comment]
Most definitely, if you are poking around and something seems weird, please say so. Would be easy to change now as Sibbell is the only thing using it. Merge whenever you want.

I poked around a little on the python 3.6 thing with Travis, I'm guessing you probably did some of the same. I'll make an issue for that, would be nice to test against 3.6...

**Comment by paulortman** [comment]
@davegaeddert 

Okay, this is now working with python 3.6 as well as everything else.  I had to be specific and explicit, but it seems like clean, obvious solution.

**Comment by paulortman** [comment]
Closes #9

**Comment by davegaeddert** [comment]
Seems good to me.

**Pull request merged**
